"""Windows normalization tests."""

import pytest

from os_normalizer import OSData, normalize_os
from tests.case_utils import build_params

WINDOWS_OSDATA_CASES = [
    (
        "Windows Windows 2012 R2 6.3.9600 6.3.9600.0 CPU:1=X64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2012 R2",
            version_major=6,
            version_minor=3,
            version_patch=0,
            version_build="9600",
            kernel_name="nt",
            kernel_version="6.3",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.3"},
            os_key="cpe:2.3:o:microsoft:windows_server_2012_r2:6.3.9600:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 19044 Enterprise x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            edition="Enterprise",
            version_major=10,
            version_minor=0,
            version_build="19044",
            kernel_name="nt",
            kernel_version="21H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_10_21h2:10.0.19044:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows Windows 7 6.1.7601 6.1.7601.0 CPU:1=I386",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 7",
            version_major=6,
            version_minor=1,
            version_patch=0,
            version_build="7601",
            kernel_name="nt",
            kernel_version="6.1",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.1"},
            os_key="cpe:2.3:o:microsoft:windows_7:6.1.7601:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows 7601 6.1.7601 6.1.7601.0 CPU:1=X64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 7",
            version_major=6,
            version_minor=1,
            version_patch=0,
            version_build="7601",
            kernel_name="nt",
            kernel_version="6.1",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.1"},
            os_key="cpe:2.3:o:microsoft:windows_7:6.1.7601:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows Windows 2008 6.1.7601 6.1.7601.0 CPU:1=X64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2008",
            version_major=6,
            version_minor=1,
            version_patch=0,
            version_build="7601",
            kernel_name="nt",
            kernel_version="6.1",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.1"},
            os_key="cpe:2.3:o:microsoft:windows_server_2008:6.1.7601:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows Windows 10 (10.0) Redstone 4 (1803) 10.0.17134 10.0.17134.81 CPU:1=X64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            version_major=10,
            version_minor=0,
            version_patch=81,
            version_build="17134",
            kernel_name="nt",
            kernel_version="1803",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_10_1803:10.0.17134:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows Windows 2003 5.2.3790 5.2.3790.0 CPU:1=I386",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2003",
            version_major=5,
            version_minor=2,
            version_patch=0,
            version_build="3790",
            kernel_name="nt",
            kernel_version="5.2",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "5.2"},
            os_key="cpe:2.3:o:microsoft:windows:5.2.3790:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows NT 6.1 Build 7601 SP1 x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 7 SP1",
            version_major=6,
            version_minor=1,
            version_build="7601",
            kernel_name="nt",
            kernel_version="6.1",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.1"},
            os_key="cpe:2.3:o:microsoft:windows:6.1.7601:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows NT 6.3 Build 9600 Professional x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 8.1",
            edition="Professional",
            version_major=6,
            version_minor=3,
            version_build="9600",
            kernel_name="nt",
            kernel_version="6.3",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.3"},
            os_key="cpe:2.3:o:microsoft:windows_8.1:6.3.9600:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows 11 Pro x86_64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Professional",
            version_major=11,
            version_minor=0,
            kernel_name="nt",
            arch="x86_64",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_11:*:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Win7 SP1 x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 7 SP1",
            version_major=6,
            version_minor=1,
            version_build="7601",
            kernel_name="nt",
            kernel_version="6.1",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows:*:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows 10 Home x86_64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            edition="Home",
            version_major=10,
            version_minor=0,
            kernel_name="nt",
            arch="x86_64",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_10:*:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 6.2 Build 9200 Enterprise x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 8",
            edition="Enterprise",
            version_major=6,
            version_minor=2,
            version_build="9200",
            kernel_name="nt",
            kernel_version="6.2",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.2"},
            os_key="cpe:2.3:o:microsoft:windows_8:6.2.9200:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows Server 2019 Datacenter x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2019",
            edition="Datacenter",
            version_major=10,
            version_minor=0,
            kernel_name="nt",
            arch="x86_64",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_server_2019:*:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows 7 Professional x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 7",
            edition="Professional",
            version_major=6,
            version_minor=1,
            version_build="7601",
            kernel_name="nt",
            kernel_version="6.1",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_7:*:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Microsoft Windows 7 Professional 6.1.7601 x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 7",
            edition="Professional",
            version_major=6,
            version_minor=1,
            version_build="7601",
            kernel_name="nt",
            kernel_version="6.1",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.1"},
            os_key="cpe:2.3:o:microsoft:windows_7:*:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows NT 10.0 build 22631 Pro ARM64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Professional",
            version_major=10,
            version_minor=0,
            version_build="22631",
            kernel_name="nt",
            kernel_version="23H2",
            arch="arm64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_11_23h2:10.0.22631:*:*:*:*:*:arm64:*",
        ),
    ),
    (
        "Windows NT 5.1 Build 2600 Professional x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows XP",
            edition="Professional",
            version_major=5,
            version_minor=1,
            version_build="2600",
            kernel_name="nt",
            kernel_version="5.1",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "5.1"},
            os_key="cpe:2.3:o:microsoft:windows:5.1.2600:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows NT 5.2 Build 3790 Server x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2003",
            version_major=5,
            version_minor=2,
            version_build="3790",
            kernel_name="nt",
            kernel_version="5.2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "5.2"},
            os_key="cpe:2.3:o:microsoft:windows:5.2.3790:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 6.0 Build 6000 Enterprise x86_64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Vista",
            edition="Enterprise",
            version_major=6,
            version_minor=0,
            version_build="6000",
            kernel_name="nt",
            kernel_version="6.0",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.0"},
            os_key="cpe:2.3:o:microsoft:windows:6.0.6000:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 19041 Home x86_64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            edition="Home",
            version_major=10,
            version_minor=0,
            version_build="19041",
            kernel_name="nt",
            kernel_version="2004",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_10_2004:10.0.19041:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 19042 Pro x86_64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            edition="Professional",
            version_major=10,
            version_minor=0,
            version_build="19042",
            kernel_name="nt",
            kernel_version="20H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_10_20h2:10.0.19042:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 19043 Education x86_64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            edition="Education",
            version_major=10,
            version_minor=0,
            version_build="19043",
            kernel_name="nt",
            kernel_version="21H1",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_10_21h1:10.0.19043:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows Server 2016 Datacenter x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2016",
            edition="Datacenter",
            version_major=10,
            version_minor=0,
            kernel_name="nt",
            arch="x86_64",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_server_2016:*:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Win11 Pro ARM64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Professional",
            version_major=11,
            version_minor=0,
            kernel_name="nt",
            arch="arm64",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_11:*:*:*:*:*:*:arm64:*",
        ),
    ),
    (
        "Windows NT 5.0 Build 2195 Professional x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 2000",
            edition="Professional",
            version_major=5,
            version_minor=0,
            version_build="2195",
            kernel_name="nt",
            kernel_version="5.0",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "5.0"},
            os_key="cpe:2.3:o:microsoft:windows:5.0.2195:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows NT 4.0 Build 1381 Professional x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows NT 4.0",
            edition="Professional",
            version_major=4,
            version_minor=0,
            version_build="1381",
            kernel_name="nt",
            kernel_version="4.0",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "4.0"},
            os_key="cpe:2.3:o:microsoft:windows:4.0.1381:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows ME Build 3000 Home x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows ME",
            edition="Home",
            version_major=4,
            version_minor=90,
            version_build="3000",
            kernel_name="nt",
            kernel_version="4.9",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows:3000:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows 98 Build 1998 Pro x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 98",
            edition="Professional",
            version_major=4,
            version_minor=10,
            version_build="1998",
            kernel_name="nt",
            kernel_version="4.10",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows:1998:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows NT 10.0 Build 25395 Windows 11 IoT Enterprise LTSC x86_64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Enterprise",
            version_major=10,
            version_minor=0,
            version_build="25395",
            kernel_name="nt",
            kernel_version="23H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_11_23h2:10.0.25395:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 Build 10586 Professional x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            edition="Professional",
            version_major=10,
            version_minor=0,
            version_build="10586",
            kernel_name="nt",
            kernel_version="1511",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_10_1511:10.0.10586:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 6.2 Build 9200 Enterprise N x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 8",
            edition="Enterprise",
            version_major=6,
            version_minor=2,
            version_build="9200",
            kernel_name="nt",
            kernel_version="6.2",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.2"},
            os_key="cpe:2.3:o:microsoft:windows_8:6.2.9200:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows NT 6.1 Build 7600 Professional x86_64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 7",
            edition="Professional",
            version_major=6,
            version_minor=1,
            version_build="7600",
            kernel_name="nt",
            kernel_version="6.1",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.1"},
            os_key="cpe:2.3:o:microsoft:windows_7:6.1.7600:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 26100 Pro x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Professional",
            version_major=10,
            version_minor=0,
            version_build="26100",
            kernel_name="nt",
            kernel_version="24H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_11_24h2:10.0.26100:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows 11 Enterprise x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Enterprise",
            version_major=11,
            version_minor=0,
            kernel_name="nt",
            arch="x86_64",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_11:*:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows 11 Home ARM64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Home",
            version_major=11,
            version_minor=0,
            kernel_name="nt",
            arch="arm64",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_11:*:*:*:*:*:*:arm64:*",
        ),
    ),
    (
        "Windows 10 Pro x86_64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            edition="Professional",
            version_major=10,
            version_minor=0,
            kernel_name="nt",
            arch="x86_64",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_10:*:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows 10 Enterprise x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            edition="Enterprise",
            version_major=10,
            version_minor=0,
            kernel_name="nt",
            arch="x86_64",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_10:*:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows Server 2022 Standard x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2022",
            edition="Standard",
            version_major=10,
            version_minor=0,
            kernel_name="nt",
            arch="x86_64",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_server_2022:*:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows Server 2019 Standard x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2019",
            edition="Standard",
            version_major=10,
            version_minor=0,
            kernel_name="nt",
            arch="x86_64",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_server_2019:*:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows Server 2012 R2 Datacenter x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2012 R2",
            edition="Datacenter",
            version_major=6,
            version_minor=3,
            version_build="9600",
            kernel_name="nt",
            kernel_version="6.3",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_server_2012_r2:*:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 22631 Enterprise x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Enterprise",
            version_major=10,
            version_minor=0,
            version_build="22631",
            kernel_name="nt",
            kernel_version="23H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_11_23h2:10.0.22631:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 19045 Enterprise x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            edition="Enterprise",
            version_major=10,
            version_minor=0,
            version_build="19045",
            kernel_name="nt",
            kernel_version="22H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_10_22h2:10.0.19045:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 6.1 SP1 Build 7601 Professional x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 7 SP1",
            edition="Professional",
            version_major=6,
            version_minor=1,
            version_build="7601",
            kernel_name="nt",
            kernel_version="6.1",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.1"},
            os_key="cpe:2.3:o:microsoft:windows:6.1.7601:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows NT 6.1 Build 7601 Server Datacenter x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2008 R2",
            edition="Datacenter",
            version_major=6,
            version_minor=1,
            version_build="7601",
            kernel_name="nt",
            kernel_version="6.1",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.1"},
            os_key="cpe:2.3:o:microsoft:windows_server_2008_r2:6.1.7601:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 6.0 Build 6001 Server Standard x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2008",
            edition="Standard",
            version_major=6,
            version_minor=0,
            version_build="6001",
            kernel_name="nt",
            kernel_version="6.0",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.0"},
            os_key="cpe:2.3:o:microsoft:windows_server_2008:6.0.6001:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows NT 6.2 Build 9200 Server Standard x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2012",
            edition="Standard",
            version_major=6,
            version_minor=2,
            version_build="9200",
            kernel_name="nt",
            kernel_version="6.2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.2"},
            os_key="cpe:2.3:o:microsoft:windows_server_2012:6.2.9200:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 6.3 Build 9600 Server Datacenter x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2012 R2",
            edition="Datacenter",
            version_major=6,
            version_minor=3,
            version_build="9600",
            kernel_name="nt",
            kernel_version="6.3",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.3"},
            os_key="cpe:2.3:o:microsoft:windows_server_2012_r2:6.3.9600:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 Build 19045 Pro x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            edition="Professional",
            version_major=10,
            version_minor=0,
            version_build="19045",
            kernel_name="nt",
            kernel_version="22H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_10_22h2:10.0.19045:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 14393 Server Datacenter x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2016",
            edition="Datacenter",
            version_major=10,
            version_minor=0,
            version_build="14393",
            kernel_name="nt",
            kernel_version="1607",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_server_2016:10.0.14393:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 17763 Server Standard x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2019",
            edition="Standard",
            version_major=10,
            version_minor=0,
            version_build="17763",
            kernel_name="nt",
            kernel_version="1809",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_server_2019:10.0.17763:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 20348 Server Datacenter x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2022",
            edition="Datacenter",
            version_major=10,
            version_minor=0,
            version_build="20348",
            kernel_name="nt",
            kernel_version="21H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_server_2022:10.0.20348:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 11.0 build 26100 Server Datacenter x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows Server 2025",
            edition="Datacenter",
            version_major=11,
            version_minor=0,
            version_build="26100",
            kernel_name="nt",
            kernel_version="24H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows:10.0.26100:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 6.1 Build 7601 SP2 x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 7 SP2",
            version_major=6,
            version_minor=1,
            version_build="7601",
            kernel_name="nt",
            kernel_version="6.1",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "6.1"},
            os_key="cpe:2.3:o:microsoft:windows:6.1.7601:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows NT 10.0 build 19044 Pro x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            edition="Professional",
            version_major=10,
            version_minor=0,
            version_build="19044",
            kernel_name="nt",
            kernel_version="21H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_10_21h2:10.0.19044:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 19044 Home x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            edition="Home",
            version_major=10,
            version_minor=0,
            version_build="19044",
            kernel_name="nt",
            kernel_version="21H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_10_21h2:10.0.19044:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 19045 Home x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 10",
            edition="Home",
            version_major=10,
            version_minor=0,
            version_build="19045",
            kernel_name="nt",
            kernel_version="22H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_10_22h2:10.0.19045:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 22000 Enterprise x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Enterprise",
            version_major=10,
            version_minor=0,
            version_build="22000",
            kernel_name="nt",
            kernel_version="21H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_11_21h2:10.0.22000:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 22000 Pro x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Professional",
            version_major=10,
            version_minor=0,
            version_build="22000",
            kernel_name="nt",
            kernel_version="21H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_11_21h2:10.0.22000:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 22000 Home x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Home",
            version_major=10,
            version_minor=0,
            version_build="22000",
            kernel_name="nt",
            kernel_version="21H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_11_21h2:10.0.22000:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 22621 Enterprise x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Enterprise",
            version_major=10,
            version_minor=0,
            version_build="22621",
            kernel_name="nt",
            kernel_version="22H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_11_22h2:10.0.22621:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 22621 Pro x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Professional",
            version_major=10,
            version_minor=0,
            version_build="22621",
            kernel_name="nt",
            kernel_version="22H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_11_22h2:10.0.22621:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 22621 Home x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Home",
            version_major=10,
            version_minor=0,
            version_build="22621",
            kernel_name="nt",
            kernel_version="22H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_11_22h2:10.0.22621:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 22631 Pro x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Professional",
            version_major=10,
            version_minor=0,
            version_build="22631",
            kernel_name="nt",
            kernel_version="23H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_11_23h2:10.0.22631:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows NT 10.0 build 22631 Home x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 11",
            edition="Home",
            version_major=10,
            version_minor=0,
            version_build="22631",
            kernel_name="nt",
            kernel_version="23H2",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows", "nt_version": "10.0"},
            os_key="cpe:2.3:o:microsoft:windows_11_23h2:10.0.22631:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Windows 7 SP1 Professional x86",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 7 SP1",
            edition="Professional",
            version_major=6,
            version_minor=1,
            version_build="7601",
            kernel_name="nt",
            kernel_version="6.1",
            arch="x86",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows:*:*:*:*:*:*:x86:*",
        ),
    ),
    (
        "Windows 8.1 Enterprise x64",
        None,
        OSData(
            family="windows",
            vendor="Microsoft",
            product="Windows 8.1",
            edition="Enterprise",
            version_major=6,
            version_minor=3,
            version_build="9600",
            kernel_name="nt",
            kernel_version="6.3",
            arch="x86_64",
            precision="build",
            confidence=0.85,
            evidence={"hit": "windows"},
            os_key="cpe:2.3:o:microsoft:windows_8.1:*:*:*:*:*:*:x64:*",
        ),
    ),
]


@pytest.mark.parametrize(("text", "data", "expected"), build_params("windows", WINDOWS_OSDATA_CASES))
def test_windows_normalize_os(text: str, data: dict | None, expected: OSData) -> None:
    """Ensure windows inputs normalize into the expected OSData payloads."""
    result = normalize_os(text, data)
    assert result == expected
