"""Comprehensive normalization tests grouped by platform."""

import pytest

from os_normalizer import OSData, normalize_os

WINDOWS_OSDATA_CASES = [
    (
        'Windows NT 10.0 build 19044 Enterprise x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 10',
            edition='Enterprise',
            channel='2004/20H2/21H1/21H2/22H2',
            version_build='19044',
            kernel_name='nt',
            kernel_version='10.0.19044',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_10_2004\\/20h2\\/21h1\\/21h2\\/22h2:10.0.19044:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 6.1 Build 7601 SP1 x86',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 7',
            version_patch=1,
            version_build='7601',
            kernel_name='nt',
            kernel_version='6.1.7601',
            arch='x86',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'service_pack': 'SP1', 'nt_version': '6.1'},
            os_key='cpe:2.3:o:microsoft:windows_7:6.1.7601:*:*:*:*:*:x86:*',
        )
    ),
    (
        'Windows NT 6.3 Build 9600 Professional x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 8.1',
            edition='Professional',
            version_build='9600',
            kernel_name='nt',
            kernel_version='6.3.9600',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '6.3'},
            os_key='cpe:2.3:o:microsoft:windows_8.1:6.3.9600:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows 11 Pro x86_64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 11',
            edition='Professional',
            version_major=11,
            kernel_name='nt',
            arch='x86_64',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows_11:*:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Win7 SP1 x86',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 7',
            version_patch=1,
            kernel_name='nt',
            arch='x86',
            precision='patch',
            confidence=0.8,
            evidence={'hit': 'windows', 'service_pack': 'SP1'},
            os_key='cpe:2.3:o:microsoft:windows_7:*:*:*:*:*:*:x86:*',
        )
    ),
    (
        'Windows 10 Home x86_64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 10',
            edition='Home',
            version_major=10,
            kernel_name='nt',
            arch='x86_64',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows_10:*:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 6.2 Build 9200 Enterprise x86',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 8',
            edition='Enterprise',
            version_build='9200',
            kernel_name='nt',
            kernel_version='6.2.9200',
            arch='x86',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '6.2'},
            os_key='cpe:2.3:o:microsoft:windows_8:6.2.9200:*:*:*:*:*:x86:*',
        )
    ),
    (
        'Windows Server 2019 Datacenter x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2019',
            edition='Datacenter',
            kernel_name='nt',
            arch='x86_64',
            precision='product',
            confidence=0.6,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows_server_2019:*:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows 7 Professional x86',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 7',
            edition='Professional',
            version_major=7,
            kernel_name='nt',
            arch='x86',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows_7:*:*:*:*:*:*:x86:*',
        )
    ),
    (
        'Windows NT 10.0 build 22631 Pro ARM64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 11',
            edition='Professional',
            channel='23H2',
            version_build='22631',
            kernel_name='nt',
            kernel_version='10.0.22631',
            arch='arm64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_11_23h2:10.0.22631:*:*:*:*:*:arm64:*',
        )
    ),
    (
        'Windows NT 5.1 Build 2600 Professional x86',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows XP',
            edition='Professional',
            version_build='2600',
            kernel_name='nt',
            kernel_version='5.1.2600',
            arch='x86',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '5.1'},
            os_key='cpe:2.3:o:microsoft:windows:5.1.2600:*:*:*:*:*:x86:*',
        )
    ),
    (
        'Windows NT 5.2 Build 3790 Server x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2003',
            version_build='3790',
            kernel_name='nt',
            kernel_version='5.2.3790',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '5.2'},
            os_key='cpe:2.3:o:microsoft:windows:5.2.3790:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 6.0 Build 6000 Enterprise x86_64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Vista',
            edition='Enterprise',
            version_build='6000',
            kernel_name='nt',
            kernel_version='6.0.6000',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '6.0'},
            os_key='cpe:2.3:o:microsoft:windows:6.0.6000:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 10.0 build 19041 Home x86_64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 10',
            edition='Home',
            channel='2004/20H2/21H1/21H2/22H2',
            version_build='19041',
            kernel_name='nt',
            kernel_version='10.0.19041',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_10_2004\\/20h2\\/21h1\\/21h2\\/22h2:10.0.19041:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 10.0 build 19042 Pro x86_64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 10',
            edition='Professional',
            channel='2004/20H2/21H1/21H2/22H2',
            version_build='19042',
            kernel_name='nt',
            kernel_version='10.0.19042',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_10_2004\\/20h2\\/21h1\\/21h2\\/22h2:10.0.19042:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 10.0 build 19043 Education x86_64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 10',
            edition='Education',
            channel='2004/20H2/21H1/21H2/22H2',
            version_build='19043',
            kernel_name='nt',
            kernel_version='10.0.19043',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_10_2004\\/20h2\\/21h1\\/21h2\\/22h2:10.0.19043:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows Server 2016 Datacenter x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2016',
            edition='Datacenter',
            kernel_name='nt',
            arch='x86_64',
            precision='product',
            confidence=0.6,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows_server_2016:*:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Win11 Pro ARM64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 11',
            edition='Professional',
            version_major=11,
            kernel_name='nt',
            arch='arm64',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows_11:*:*:*:*:*:*:arm64:*',
        )
    ),
    (
        'Windows NT 5.0 Build 2195 Professional x86',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 2000',
            edition='Professional',
            version_build='2195',
            kernel_name='nt',
            kernel_version='5.0.2195',
            arch='x86',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '5.0'},
            os_key='cpe:2.3:o:microsoft:windows:5.0.2195:*:*:*:*:*:x86:*',
        )
    ),
    (
        'Windows NT 4.0 Build 1381 Professional x86',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows NT 4.0',
            edition='Professional',
            version_build='1381',
            kernel_name='nt',
            kernel_version='4.0.1381',
            arch='x86',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '4.0'},
            os_key='cpe:2.3:o:microsoft:windows:4.0.1381:*:*:*:*:*:x86:*',
        )
    ),
    (
        'Windows ME Build 3000 Home x86',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows ME',
            edition='Home',
            version_build='3000',
            kernel_name='nt',
            arch='x86',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows:3000:*:*:*:*:*:x86:*',
        )
    ),
    (
        'Windows 98 Build 1998 Pro x86',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 98',
            edition='Professional',
            version_build='1998',
            kernel_name='nt',
            arch='x86',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows:1998:*:*:*:*:*:x86:*',
        )
    ),
    (
        'Windows NT 10.0 Build 25395 Windows 11 IoT Enterprise LTSC x86_64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 11',
            edition='Enterprise',
            channel='23H2',
            version_build='25395',
            kernel_name='nt',
            kernel_version='10.0.25395',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_11_23h2:10.0.25395:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 10.0 Build 10586 Professional x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 10',
            edition='Professional',
            channel='1511',
            version_build='10586',
            kernel_name='nt',
            kernel_version='10.0.10586',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_10_1511:10.0.10586:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 6.2 Build 9200 Enterprise N x86',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 8',
            edition='Enterprise',
            version_build='9200',
            kernel_name='nt',
            kernel_version='6.2.9200',
            arch='x86',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '6.2'},
            os_key='cpe:2.3:o:microsoft:windows_8:6.2.9200:*:*:*:*:*:x86:*',
        )
    ),
    (
        'Windows NT 6.1 Build 7600 Professional x86_64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 7',
            edition='Professional',
            version_build='7600',
            kernel_name='nt',
            kernel_version='6.1.7600',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '6.1'},
            os_key='cpe:2.3:o:microsoft:windows_7:6.1.7600:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 10.0 build 26100 Pro x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 11',
            edition='Professional',
            channel='24H2',
            version_build='26100',
            kernel_name='nt',
            kernel_version='10.0.26100',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_11_24h2:10.0.26100:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows 11 Enterprise x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 11',
            edition='Enterprise',
            version_major=11,
            kernel_name='nt',
            arch='x86_64',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows_11:*:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows 11 Home ARM64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 11',
            edition='Home',
            version_major=11,
            kernel_name='nt',
            arch='arm64',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows_11:*:*:*:*:*:*:arm64:*',
        )
    ),
    (
        'Windows 10 Pro x86_64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 10',
            edition='Professional',
            version_major=10,
            kernel_name='nt',
            arch='x86_64',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows_10:*:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows 10 Enterprise x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 10',
            edition='Enterprise',
            version_major=10,
            kernel_name='nt',
            arch='x86_64',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows_10:*:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows Server 2022 Standard x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2022',
            edition='Standard',
            kernel_name='nt',
            arch='x86_64',
            precision='product',
            confidence=0.6,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows_server_2022:*:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows Server 2019 Standard x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2019',
            edition='Standard',
            kernel_name='nt',
            arch='x86_64',
            precision='product',
            confidence=0.6,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows_server_2019:*:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows Server 2012 R2 Datacenter x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2012 R2',
            edition='Datacenter',
            kernel_name='nt',
            arch='x86_64',
            precision='product',
            confidence=0.6,
            evidence={'hit': 'windows'},
            os_key='cpe:2.3:o:microsoft:windows_server_2012_r2:*:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 10.0 build 22631 Enterprise x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 11',
            edition='Enterprise',
            channel='23H2',
            version_build='22631',
            kernel_name='nt',
            kernel_version='10.0.22631',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_11_23h2:10.0.22631:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 10.0 build 19045 Enterprise x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 10',
            edition='Enterprise',
            channel='2004/20H2/21H1/21H2/22H2',
            version_build='19045',
            kernel_name='nt',
            kernel_version='10.0.19045',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_10_2004\\/20h2\\/21h1\\/21h2\\/22h2:10.0.19045:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 6.1 SP1 Build 7601 Professional x86',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 7',
            edition='Professional',
            version_patch=1,
            version_build='7601',
            kernel_name='nt',
            kernel_version='6.1.7601',
            arch='x86',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'service_pack': 'SP1', 'nt_version': '6.1'},
            os_key='cpe:2.3:o:microsoft:windows_7:6.1.7601:*:*:*:*:*:x86:*',
        )
    ),
    (
        'Windows NT 6.1 Build 7601 Server Datacenter x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2008 R2',
            edition='Datacenter',
            version_build='7601',
            kernel_name='nt',
            kernel_version='6.1.7601',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '6.1'},
            os_key='cpe:2.3:o:microsoft:windows_server_2008_r2:6.1.7601:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 6.0 Build 6001 Server Standard x86',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2008',
            edition='Standard',
            version_build='6001',
            kernel_name='nt',
            kernel_version='6.0.6001',
            arch='x86',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '6.0'},
            os_key='cpe:2.3:o:microsoft:windows_server_2008:6.0.6001:*:*:*:*:*:x86:*',
        )
    ),
    (
        'Windows NT 6.2 Build 9200 Server Standard x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2012',
            edition='Standard',
            version_build='9200',
            kernel_name='nt',
            kernel_version='6.2.9200',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '6.2'},
            os_key='cpe:2.3:o:microsoft:windows_server_2012:6.2.9200:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 6.3 Build 9600 Server Datacenter x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2012 R2',
            edition='Datacenter',
            version_build='9600',
            kernel_name='nt',
            kernel_version='6.3.9600',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '6.3'},
            os_key='cpe:2.3:o:microsoft:windows_server_2012_r2:6.3.9600:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 10.0 Build 19045 Pro x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 10',
            edition='Professional',
            channel='2004/20H2/21H1/21H2/22H2',
            version_build='19045',
            kernel_name='nt',
            kernel_version='10.0.19045',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_10_2004\\/20h2\\/21h1\\/21h2\\/22h2:10.0.19045:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 10.0 build 14393 Server Datacenter x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2016',
            edition='Datacenter',
            channel='1607',
            version_build='14393',
            kernel_name='nt',
            kernel_version='10.0.14393',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_server_2016:10.0.14393:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 10.0 build 17763 Server Standard x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2019',
            edition='Standard',
            channel='1809',
            version_build='17763',
            kernel_name='nt',
            kernel_version='10.0.17763',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_server_2019:10.0.17763:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 10.0 build 20348 Server Datacenter x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2022',
            edition='Datacenter',
            channel='21H2',
            version_build='20348',
            kernel_name='nt',
            kernel_version='10.0.20348',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows_server_2022:10.0.20348:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 10.0 build 26100 Server Datacenter x64',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows Server 2025',
            edition='Datacenter',
            channel='24H2',
            version_build='26100',
            kernel_name='nt',
            kernel_version='10.0.26100',
            arch='x86_64',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '10.0'},
            os_key='cpe:2.3:o:microsoft:windows:10.0.26100:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Windows NT 6.1 Build 7601 SP2 x86',
        None,
        OSData(
            family='windows',
            vendor='Microsoft',
            product='Windows 7',
            version_patch=2,
            version_build='7601',
            kernel_name='nt',
            kernel_version='6.1.7601',
            arch='x86',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'windows', 'nt_version': '6.1', 'service_pack': 'SP2'},
        )
    ),
]

MACOS_OSDATA_CASES = [
    (
        'Darwin Mac-Studio.local 25.0.0 Darwin Kernel Version 25.0.0: Mon Aug 25 21:17:54 PDT 2025; root:xnu-12377.1.9~3/RELEASE_ARM64_T6041 arm64',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Tahoe',
            version_major=26,
            kernel_name='darwin',
            kernel_version='25.0.0',
            arch='arm64',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:26.0:*:*:*:*:*:arm64:*',
        )
    ),
    (
        'Darwin 22.3.0; macOS',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Ventura',
            version_major=13,
            kernel_name='darwin',
            kernel_version='22.3.0',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:13.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'macOS Ventura Darwin 22.0.0',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Ventura',
            version_major=13,
            kernel_name='darwin',
            kernel_version='22.0.0',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:13.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'macOS Monterey Darwin 21.0.0',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Monterey',
            version_major=12,
            kernel_name='darwin',
            kernel_version='21.0.0',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:12.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'Darwin 23.4.0; macOS Big Sur',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Sonoma',
            version_major=14,
            kernel_name='darwin',
            kernel_version='23.4.0',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:14.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'macOS Sequoia Darwin 24.0.0',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Sequoia',
            version_major=15,
            kernel_name='darwin',
            kernel_version='24.0.0',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:15.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'Darwin 8.0.0; Mac OS X',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            kernel_name='darwin',
            kernel_version='8.0.0',
            confidence=0.6,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:*:*:*:*:*:*:*:*',
        )
    ),
    (
        'Darwin 9.0.0; Mac OS X',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            kernel_name='darwin',
            kernel_version='9.0.0',
            confidence=0.6,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:*:*:*:*:*:*:*:*',
        )
    ),
    (
        'Darwin 19.6.0; macOS Catalina',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Catalina',
            version_major=10,
            version_minor=15,
            kernel_name='darwin',
            kernel_version='19.6.0',
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:10.15:*:*:*:*:*:*:*',
        )
    ),
    (
        'Darwin 20.6.0; macOS Big Sur',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Big Sur',
            version_major=11,
            kernel_name='darwin',
            kernel_version='20.6.0',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:11.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'Darwin 21.6.0; macOS Monterey',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Monterey',
            version_major=12,
            kernel_name='darwin',
            kernel_version='21.6.0',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:12.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'Darwin 22.6.0; macOS Ventura',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Ventura',
            version_major=13,
            kernel_name='darwin',
            kernel_version='22.6.0',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:13.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'Darwin 23.6.0; macOS Sonoma',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Sonoma',
            version_major=14,
            kernel_name='darwin',
            kernel_version='23.6.0',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:14.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'Darwin 24.6.0; macOS Sequoia',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Sequoia',
            version_major=15,
            kernel_name='darwin',
            kernel_version='24.6.0',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:15.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'Darwin 22.5.0; macOS',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Ventura',
            version_major=13,
            kernel_name='darwin',
            kernel_version='22.5.0',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:13.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'Darwin 23.5.0; macOS',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Sonoma',
            version_major=14,
            kernel_name='darwin',
            kernel_version='23.5.0',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:14.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'Darwin 24.5.0; macOS',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Sequoia',
            version_major=15,
            kernel_name='darwin',
            kernel_version='24.5.0',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:15.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'Darwin 22.0.0; macOS arm64',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Ventura',
            version_major=13,
            kernel_name='darwin',
            kernel_version='22.0.0',
            arch='arm64',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:13.0:*:*:*:*:*:arm64:*',
        )
    ),
    (
        'Darwin 23.0.0; macOS x86_64',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Sonoma',
            version_major=14,
            kernel_name='darwin',
            kernel_version='23.0.0',
            arch='x86_64',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:14.0:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Darwin 24.0.0; macOS x86_64',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Sequoia',
            version_major=15,
            kernel_name='darwin',
            kernel_version='24.0.0',
            arch='x86_64',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:15.0:*:*:*:*:*:x64:*',
        )
    ),
    (
        'macOS 14.0',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            version_major=14,
            version_minor=0,
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:14.0:*:*:*:*:*:*:*',
        )
    ),
    (
        'macOS 13.5',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            version_major=13,
            version_minor=5,
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:13.5:*:*:*:*:*:*:*',
        )
    ),
    (
        'macOS 12.6',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            version_major=12,
            version_minor=6,
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:12.6:*:*:*:*:*:*:*',
        )
    ),
    (
        'macOS 11.7',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            version_major=11,
            version_minor=7,
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'macos'},
            os_key='cpe:2.3:o:apple:macos:11.7:*:*:*:*:*:*:*',
        )
    ),
    (
        'macOS Sequoia',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Sequoia',
            version_major=15,
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
        )
    ),
    (
        'Darwin 24.0.0; macOS Sequoia arm64',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Sequoia',
            version_major=15,
            kernel_name='darwin',
            kernel_version='24.0.0',
            arch='arm64',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
        )
    ),
    (
        'macOS Ventura Darwin 22.0.0 x86_64',
        None,
        OSData(
            family='macos',
            vendor='Apple',
            product='macOS',
            codename='Ventura',
            version_major=13,
            kernel_name='darwin',
            kernel_version='22.0.0',
            arch='x86_64',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'macos'},
        )
    ),
]

LINUX_OSDATA_CASES = [
    (
        'Linux host 5.15.0-122-generic x86_64',
        {'os_release': 'NAME="Ubuntu"\nID=ubuntu\nVERSION_ID="22.04.4"\nVERSION_CODENAME=jammy'},
        OSData(
            family='linux',
            vendor='Canonical',
            product='Ubuntu',
            codename='Jammy',
            version_major=22,
            version_minor=4,
            version_patch=4,
            kernel_name='linux',
            kernel_version='5.15.0-122-generic',
            arch='x86_64',
            distro='ubuntu',
            pretty_name='Ubuntu',
            precision='patch',
            confidence=0.8,
            evidence={'hit': 'linux'},
            os_key='cpe:2.3:o:canonical:ubuntu_linux:22.04:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Linux host 5.10.0-30-amd64',
        {'os_release': 'NAME="Debian GNU/Linux"\nID=debian\nVERSION_ID="12"\nVERSION_CODENAME=bookworm'},
        OSData(
            family='linux',
            vendor='Debian',
            product='Debian GNU/Linux',
            codename='Bookworm',
            version_major=12,
            kernel_name='linux',
            kernel_version='5.10.0-30-amd64',
            arch='x86_64',
            distro='debian',
            pretty_name='Debian GNU/Linux',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'linux'},
            os_key='cpe:2.3:o:debian:debian_linux:12:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Linux node 6.5.7-arch1-1',
        {'os_release': 'NAME="Arch Linux"\nID=arch\nVERSION_ID="rolling"'},
        OSData(
            family='linux',
            vendor='Arch',
            product='Arch Linux',
            kernel_name='linux',
            kernel_version='6.5.7-arch1-1',
            distro='arch',
            pretty_name='Arch Linux',
            precision='family',
            confidence=0.6,
            evidence={'hit': 'linux'},
            os_key='cpe:2.3:o:arch:arch\\ linux:*:*:*:*:*:*:*:*',
        )
    ),
    (
        'Linux host 4.18.0-553.8.1.el8_10.x86_64',
        {'os_release': 'NAME="Red Hat Enterprise Linux"\n            ID=rhel\n            VERSION_ID="8.10"\n            PRETTY_NAME="Red Hat Enterprise Linux 8.10 (Ootpa)"'},
        OSData(
            family='linux',
            vendor='Red Hat',
            product='Red Hat Enterprise Linux',
            codename='Ootpa',
            version_major=8,
            version_minor=10,
            kernel_name='linux',
            kernel_version='4.18.0-553.8.1.el8_10.x86_64',
            arch='x86_64',
            distro='rhel',
            pretty_name='Red Hat Enterprise Linux 8.10 (Ootpa)',
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'linux'},
            os_key='cpe:2.3:o:redhat:enterprise_linux:8:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Linux host 5.4.0-105-amd64',
        {'os_release': 'NAME="Rocky Linux"\nID=rocky\nVERSION_ID="9.4"\nPRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"'},
        OSData(
            family='linux',
            vendor='Rocky',
            product='Rocky Linux',
            codename='Blue Onyx',
            version_major=9,
            version_minor=4,
            kernel_name='linux',
            kernel_version='5.4.0-105-amd64',
            arch='x86_64',
            distro='rocky',
            pretty_name='Rocky Linux 9.4 (Blue Onyx)',
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'linux'},
            os_key='cpe:2.3:o:rocky:rocky\\ linux:9.4:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Linux host 5.15.0-122-generic aarch64',
        {'os_release': 'NAME="AlmaLinux"\nID=almalinux\nVERSION_ID="9.4"\nPRETTY_NAME="AlmaLinux 9.4 (Seafoam Ocelot)"'},
        OSData(
            family='linux',
            vendor='AlmaLinux',
            product='AlmaLinux',
            codename='Seafoam Ocelot',
            version_major=9,
            version_minor=4,
            kernel_name='linux',
            kernel_version='5.15.0-122-generic',
            arch='arm64',
            distro='almalinux',
            pretty_name='AlmaLinux 9.4 (Seafoam Ocelot)',
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'linux'},
            os_key='cpe:2.3:o:almalinux:almalinux:9.4:*:*:*:*:*:arm64:*',
        )
    ),
    (
        'Linux host 5.15.0-122-generic arm64',
        {'os_release': 'NAME="Amazon Linux"\nID=amzn\nVERSION_ID="2023"\nPRETTY_NAME="Amazon Linux 2023"'},
        OSData(
            family='linux',
            vendor='Amazon',
            product='Amazon Linux',
            version_major=2023,
            kernel_name='linux',
            kernel_version='5.15.0-122-generic',
            arch='arm64',
            distro='amzn',
            pretty_name='Amazon Linux 2023',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'linux'},
            os_key='cpe:2.3:o:amazon:amazon_linux:2023:*:*:*:*:*:arm64:*',
        )
    ),
    (
        'Linux host 3.10.0-862.el7.x86_64',
        {'os_release': 'NAME="CentOS Linux"\nID=centos\nVERSION_ID="7"\nPRETTY_NAME="CentOS Linux 7 (Core)"'},
        OSData(
            family='linux',
            vendor='Red Hat',
            product='CentOS Linux',
            codename='Core',
            version_major=7,
            kernel_name='linux',
            kernel_version='3.10.0-862.el7.x86_64',
            arch='x86_64',
            distro='centos',
            pretty_name='CentOS Linux 7 (Core)',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'linux'},
            os_key='cpe:2.3:o:red\\ hat:centos\\ linux:7:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Linux host 5.14.0-70.fc33.x86_64',
        {'os_release': 'NAME="Fedora Linux"\nID=fedora\nVERSION_ID="33"\nPRETTY_NAME="Fedora Linux 33 (Workstation Edition)"'},
        OSData(
            family='linux',
            vendor='Fedora Project',
            product='Fedora Linux',
            codename='Workstation Edition',
            version_major=33,
            kernel_name='linux',
            kernel_version='5.14.0-70.fc33.x86_64',
            arch='x86_64',
            distro='fedora',
            pretty_name='Fedora Linux 33 (Workstation Edition)',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'linux'},
            os_key='cpe:2.3:o:fedoraproject:fedora:33:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Linux host 4.19.0-18-amd64',
        {'os_release': 'NAME="Debian GNU/Linux"\nID=debian\nVERSION_ID="10"\nPRETTY_NAME="Debian GNU/Linux 10 (buster)"'},
        OSData(
            family='linux',
            vendor='Debian',
            product='Debian GNU/Linux',
            codename='Buster',
            version_major=10,
            kernel_name='linux',
            kernel_version='4.19.0-18-amd64',
            arch='x86_64',
            distro='debian',
            pretty_name='Debian GNU/Linux 10 (buster)',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'linux'},
            os_key='cpe:2.3:o:debian:debian_linux:10:*:*:*:*:*:x64:*',
        )
    ),
    (
        'Linux node 6.5.7-arch1-1',
        None,
        OSData(
            family='linux',
            product='Linux',
            kernel_name='linux',
            kernel_version='6.5.7-arch1-1',
            precision='family',
            confidence=0.6,
            evidence={'hit': 'linux'},
        )
    ),
    (
        'Linux host 5.4.0-70-generic',
        {'os_release': {'NAME': 'Fedora Linux', 'ID': 'fedora', 'VERSION_ID': '33'}},
        OSData(
            family='linux',
            vendor='Fedora Project',
            product='Fedora Linux',
            version_major=33,
            kernel_name='linux',
            kernel_version='5.4.0-70-generic',
            distro='fedora',
            pretty_name='Fedora Linux',
            precision='major',
            confidence=0.7,
            evidence={'hit': 'linux'},
        )
    ),
    (
        'Linux host 5.15.0-122-generic x86_64',
        {'os_release': 'NAME="Ubuntu"\nID=ubuntu\nVERSION_ID="22.04.4"\nVERSION_CODENAME=jammy\nPRETTY_NAME="Ubuntu 22.04.4 LTS"'},
        OSData(
            family='linux',
            vendor='Canonical',
            product='Ubuntu',
            codename='Jammy',
            channel='LTS',
            version_major=22,
            version_minor=4,
            version_patch=4,
            kernel_name='linux',
            kernel_version='5.15.0-122-generic',
            arch='x86_64',
            distro='ubuntu',
            pretty_name='Ubuntu 22.04.4 LTS',
            precision='patch',
            confidence=0.8,
            evidence={'hit': 'linux'},
        )
    ),
]

MOBILE_OSDATA_CASES = [
    (
        'Android 14 build UPB5.230623.003',
        None,
        OSData(
            family='android',
            vendor='Google',
            product='Android',
            version_major=14,
            precision='major',
            confidence=0.7,
            evidence={'hit': 'android'},
            os_key='cpe:2.3:o:google:android:14:*:*:*:*:*:*:*',
        )
    ),
    (
        'iOS 17.5.1',
        None,
        OSData(
            family='ios',
            vendor='Apple',
            product='iOS/iPadOS',
            version_major=17,
            version_minor=5,
            version_patch=1,
            precision='patch',
            confidence=0.8,
            evidence={'hit': 'ios'},
            os_key='cpe:2.3:o:apple:iphone_os:17.5.1:*:*:*:*:*:*:*',
        )
    ),
    (
        'iPadOS 16.7.6',
        None,
        OSData(
            family='ios',
            vendor='Apple',
            product='iOS/iPadOS',
            version_major=16,
            version_minor=7,
            version_patch=6,
            precision='patch',
            confidence=0.8,
            evidence={'hit': 'ios'},
            os_key='cpe:2.3:o:apple:iphone_os:16.7.6:*:*:*:*:*:*:*',
        )
    ),
]

BSD_OSDATA_CASES = [
    (
        'FreeBSD 12.4-RELEASE',
        None,
        OSData(
            family='bsd',
            vendor='FreeBSD',
            product='FreeBSD',
            channel='RELEASE',
            version_major=12,
            version_minor=4,
            kernel_name='freebsd',
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'bsd'},
            os_key='cpe:2.3:o:freebsd:freebsd:12.4:*:*:*:*:*:*:*',
        )
    ),
    (
        'OpenBSD 7.5',
        None,
        OSData(
            family='bsd',
            vendor='OpenBSD',
            product='OpenBSD',
            version_major=7,
            version_minor=5,
            kernel_name='openbsd',
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'bsd'},
            os_key='cpe:2.3:o:openbsd:openbsd:7.5:*:*:*:*:*:*:*',
        )
    ),
    (
        'NetBSD 9.3',
        None,
        OSData(
            family='bsd',
            vendor='NetBSD',
            product='NetBSD',
            version_major=9,
            version_minor=3,
            kernel_name='netbsd',
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'bsd'},
        )
    ),
    (
        'FreeBSD 13.2-RC1',
        None,
        OSData(
            family='bsd',
            vendor='FreeBSD',
            product='FreeBSD',
            channel='RC1',
            version_major=13,
            version_minor=2,
            kernel_name='freebsd',
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'bsd'},
        )
    ),
    (
        'FreeBSD 13.3-STABLE',
        None,
        OSData(
            family='bsd',
            vendor='FreeBSD',
            product='FreeBSD',
            channel='STABLE',
            version_major=13,
            version_minor=3,
            kernel_name='freebsd',
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'bsd'},
        )
    ),
    (
        'OpenBSD 7.6 current',
        None,
        OSData(
            family='bsd',
            vendor='OpenBSD',
            product='OpenBSD',
            channel='CURRENT',
            version_major=7,
            version_minor=6,
            kernel_name='openbsd',
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'bsd'},
        )
    ),
    (
        'NetBSD 10.0_BETA',
        None,
        OSData(
            family='bsd',
            vendor='NetBSD',
            product='NetBSD',
            channel='BETA',
            version_major=10,
            version_minor=0,
            kernel_name='netbsd',
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'bsd'},
        )
    ),
]

NETWORK_OSDATA_CASES = [
    (
        'Cisco IOS XE Software, Version 17.9.1a (Amsterdam) C9300-24T, universalk9, c9300-universalk9.17.9.1a.SPA.bin',
        None,
        OSData(
            family='network-os',
            vendor='Cisco',
            product='IOS XE',
            edition='universalk9',
            codename='Amsterdam',
            version_major=17,
            version_minor=9,
            version_patch=1,
            version_build='17.9.1a',
            kernel_name='ios-xe',
            hw_model='C9300-24T',
            build_id='c9300-universalk9.17.9.1a.SPA.bin',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'network-os', 'version_raw': '17.9.1a'},
            os_key='cpe:2.3:o:cisco:ios_xe:17.9.1a:*:universalk9:*:*:*:*:*',
        )
    ),
    (
        'Cisco Nexus Operating System (NX-OS) Software nxos.9.3(5).bin N9K-C93180YC-FX',
        None,
        OSData(
            family='network-os',
            vendor='Cisco',
            product='NX-OS',
            version_major=9,
            version_minor=3,
            version_patch=5,
            version_build='9.3(5)',
            kernel_name='nx-os',
            hw_model='N9K-C93180YC-FX',
            precision='patch',
            confidence=0.8,
            evidence={'hit': 'network-os', 'version_raw': '9.3(5)'},
            os_key='cpe:2.3:o:cisco:nx-os:9.3\\(5\\):*:*:*:*:*:*:*',
        )
    ),
    (
        'Junos: 20.4R3-S3 jinstall-ex-4300-20.4R3-S3.tgz EX4300-48T',
        None,
        OSData(
            family='network-os',
            vendor='Juniper',
            product='Junos',
            version_major=20,
            version_minor=4,
            version_build='20.4R3-S3',
            kernel_name='junos',
            hw_model='EX4300-48T',
            build_id='jinstall-ex-4300-20.4R3-S3.tgz',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'network-os', 'version_raw': '20.4R3-S3'},
            os_key='cpe:2.3:o:juniper:junos:20.4r3-s3:*:*:*:*:*:*:*',
        )
    ),
    (
        'FortiGate-100F v7.2.7 build1600 (GA) FGT_7.2.7-build1600',
        None,
        OSData(
            family='network-os',
            vendor='Fortinet',
            product='FortiOS',
            channel='GA',
            version_major=7,
            version_minor=2,
            version_patch=7,
            version_build='7.2.7+build.1600',
            kernel_name='fortios',
            hw_model='FG-100F',
            build_id='FGT_7.2.7-build1600',
            precision='build',
            confidence=0.85,
            evidence={'hit': 'network-os'},
            os_key='cpe:2.3:o:fortinet:fortios:7.2.7:*:*:*:*:*:*:*',
        )
    ),
    (
        'Huawei VRP V800R012C00SPC500 S5720-28X-SI-AC',
        None,
        OSData(
            family='network-os',
            vendor='Huawei',
            product='VRP',
            version_major=800,
            version_minor=12,
            version_build='V800R012C00SPC500',
            kernel_name='vrp',
            hw_model='S5720-28X-SI-AC',
            build_id='V800R012C00SPC500',
            precision='minor',
            confidence=0.75,
            evidence={'hit': 'network-os'},
        )
    ),
    (
        'NETGEAR Firmware V1.0.9.88_10.2.88 R7000',
        None,
        OSData(
            family='network-os',
            vendor='Netgear',
            product='Firmware',
            version_major=1,
            version_minor=0,
            version_patch=9,
            version_build='1.0.9.88_10.2.88',
            kernel_name='firmware',
            hw_model='R7000',
            precision='patch',
            confidence=0.8,
            evidence={'hit': 'network-os'},
        )
    ),
]

CASE_GROUPS = [
    ("windows", WINDOWS_OSDATA_CASES),
    ("macos", MACOS_OSDATA_CASES),
    ("linux", LINUX_OSDATA_CASES),
    ("mobile", MOBILE_OSDATA_CASES),
    ("bsd", BSD_OSDATA_CASES),
    ("network", NETWORK_OSDATA_CASES),
]


def safe_id(text: str) -> str:
    """Return a short, pytest-friendly identifier."""
    return text.replace(" ", "_").replace("/", "_").replace(".", "_")[:30]


def create_osdata_parameters() -> list:
    """Flatten platform groups into pytest parameters."""
    params = []
    for group, cases in CASE_GROUPS:
        for idx, (raw, data, expected) in enumerate(cases):
            params.append(
                pytest.param(
                    raw,
                    data,
                    expected,
                    id=f"{group}_{idx:03d}_{safe_id(raw)}",
                )
            )
    return params


@pytest.mark.parametrize(("text", "data", "expected"), create_osdata_parameters())
def test_normalize_os_matches_expected(text: str, data: dict | None, expected: OSData) -> None:
    """Ensure normalize_os yields the expected OSData structure for every fixture."""
    result = normalize_os(text, data)
    assert result == expected

