"""macOS normalization tests."""

import pytest

from os_normalizer import OSData, normalize_os
from tests.case_utils import build_params

MACOS_OSDATA_CASES = [
    (
        "Darwin Mac-Studio.local 25.0.0 Darwin Kernel Version 25.0.0: Mon Aug 25 21:17:54 PDT 2025; root:xnu-12377.1.9~3/RELEASE_ARM64_T6041 arm64",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Tahoe",
            version_major=26,
            kernel_name="darwin",
            kernel_version="25.0.0",
            arch="arm64",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:26.0:*:*:*:*:*:arm64:*",
        ),
    ),
    (
        "Darwin 22.3.0; macOS",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Ventura",
            version_major=13,
            kernel_name="darwin",
            kernel_version="22.3.0",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:13.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "macOS Ventura Darwin 22.0.0",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Ventura",
            version_major=13,
            kernel_name="darwin",
            kernel_version="22.0.0",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:13.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "macOS Monterey Darwin 21.0.0",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Monterey",
            version_major=12,
            kernel_name="darwin",
            kernel_version="21.0.0",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:12.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Darwin 23.4.0; macOS Big Sur",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Sonoma",
            version_major=14,
            kernel_name="darwin",
            kernel_version="23.4.0",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:14.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "macOS Sequoia Darwin 24.0.0",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Sequoia",
            version_major=15,
            kernel_name="darwin",
            kernel_version="24.0.0",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:15.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Darwin 8.0.0; Mac OS X",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            kernel_name="darwin",
            kernel_version="8.0.0",
            confidence=0.6,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:*:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Darwin 9.0.0; Mac OS X",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            kernel_name="darwin",
            kernel_version="9.0.0",
            confidence=0.6,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:*:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Darwin 19.6.0; macOS Catalina",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Catalina",
            version_major=10,
            version_minor=15,
            kernel_name="darwin",
            kernel_version="19.6.0",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:10.15:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Darwin 20.6.0; macOS Big Sur",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Big Sur",
            version_major=11,
            kernel_name="darwin",
            kernel_version="20.6.0",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:11.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Darwin 21.6.0; macOS Monterey",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Monterey",
            version_major=12,
            kernel_name="darwin",
            kernel_version="21.6.0",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:12.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Darwin 22.6.0; macOS Ventura",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Ventura",
            version_major=13,
            kernel_name="darwin",
            kernel_version="22.6.0",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:13.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Darwin 23.6.0; macOS Sonoma",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Sonoma",
            version_major=14,
            kernel_name="darwin",
            kernel_version="23.6.0",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:14.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Darwin 24.6.0; macOS Sequoia",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Sequoia",
            version_major=15,
            kernel_name="darwin",
            kernel_version="24.6.0",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:15.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Darwin 22.5.0; macOS",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Ventura",
            version_major=13,
            kernel_name="darwin",
            kernel_version="22.5.0",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:13.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Darwin 23.5.0; macOS",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Sonoma",
            version_major=14,
            kernel_name="darwin",
            kernel_version="23.5.0",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:14.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Darwin 24.5.0; macOS",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Sequoia",
            version_major=15,
            kernel_name="darwin",
            kernel_version="24.5.0",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:15.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Darwin 22.0.0; macOS arm64",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Ventura",
            version_major=13,
            kernel_name="darwin",
            kernel_version="22.0.0",
            arch="arm64",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:13.0:*:*:*:*:*:arm64:*",
        ),
    ),
    (
        "Darwin 23.0.0; macOS x86_64",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Sonoma",
            version_major=14,
            kernel_name="darwin",
            kernel_version="23.0.0",
            arch="x86_64",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:14.0:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "Darwin 24.0.0; macOS x86_64",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Sequoia",
            version_major=15,
            kernel_name="darwin",
            kernel_version="24.0.0",
            arch="x86_64",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:15.0:*:*:*:*:*:x64:*",
        ),
    ),
    (
        "macOS 14.0",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            version_major=14,
            version_minor=0,
            precision="minor",
            confidence=0.75,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:14.0:*:*:*:*:*:*:*",
        ),
    ),
    (
        "macOS 13.5",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            version_major=13,
            version_minor=5,
            precision="minor",
            confidence=0.75,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:13.5:*:*:*:*:*:*:*",
        ),
    ),
    (
        "macOS 12.6",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            version_major=12,
            version_minor=6,
            precision="minor",
            confidence=0.75,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:12.6:*:*:*:*:*:*:*",
        ),
    ),
    (
        "macOS 11.7",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            version_major=11,
            version_minor=7,
            precision="minor",
            confidence=0.75,
            evidence={"hit": "macos"},
            os_key="cpe:2.3:o:apple:macos:11.7:*:*:*:*:*:*:*",
        ),
    ),
    (
        "macOS Sequoia",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Sequoia",
            version_major=15,
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
        ),
    ),
    (
        "Darwin 24.0.0; macOS Sequoia arm64",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Sequoia",
            version_major=15,
            kernel_name="darwin",
            kernel_version="24.0.0",
            arch="arm64",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
        ),
    ),
    (
        "macOS Ventura Darwin 22.0.0 x86_64",
        None,
        OSData(
            family="macos",
            vendor="Apple",
            product="macOS",
            codename="Ventura",
            version_major=13,
            kernel_name="darwin",
            kernel_version="22.0.0",
            arch="x86_64",
            precision="major",
            confidence=0.7,
            evidence={"hit": "macos"},
        ),
    ),
]


@pytest.mark.parametrize(("text", "data", "expected"), build_params("macos", MACOS_OSDATA_CASES))
def test_macos_normalize_os(text: str, data: dict | None, expected: OSData) -> None:
    """Ensure macos inputs normalize into the expected OSData payloads."""
    result = normalize_os(text, data)
    assert result == expected
