"""Network OS normalization tests."""

import pytest

from os_normalizer import OSData, normalize_os
from tests.case_utils import build_params

NETWORK_OSDATA_CASES = [
    (
        "Cisco IOS XE Software, Version 17.9.1a (Amsterdam) C9300-24T, universalk9, c9300-universalk9.17.9.1a.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="universalk9",
            codename="Amsterdam",
            version_major=17,
            version_minor=9,
            version_patch=1,
            version_build="17.9.1a",
            kernel_name="ios-xe",
            hw_model="C9300-24T",
            build_id="c9300-universalk9.17.9.1a.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.9.1a"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.9.1a:*:universalk9:*:*:*:*:*",
        ),
    ),
    (
        "Cisco Nexus Operating System (NX-OS) Software nxos.9.3(5).bin N9K-C93180YC-FX",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="NX-OS",
            version_major=9,
            version_minor=3,
            version_patch=5,
            version_build="9.3(5)",
            kernel_name="nx-os",
            hw_model="N9K-C93180YC-FX",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os", "version_raw": "9.3(5)"},
            os_key="cpe:2.3:o:cisco:nx-os:9.3\\(5\\):*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 20.4R3-S3 jinstall-ex-4300-20.4R3-S3.tgz EX4300-48T",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=20,
            version_minor=4,
            version_build="20.4R3-S3",
            kernel_name="junos",
            hw_model="EX4300-48T",
            build_id="jinstall-ex-4300-20.4R3-S3.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "20.4R3-S3"},
            os_key="cpe:2.3:o:juniper:junos:20.4r3-s3:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-100F v7.2.7 build1600 (GA) FGT_7.2.7-build1600",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=7,
            version_minor=2,
            version_patch=7,
            version_build="7.2.7+build.1600",
            kernel_name="fortios",
            hw_model="FG-100F",
            build_id="FGT_7.2.7-build1600",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.2.7:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Huawei VRP V800R012C00SPC500 S5720-28X-SI-AC",
        None,
        OSData(
            family="network-os",
            vendor="Huawei",
            product="VRP",
            version_major=800,
            version_minor=12,
            version_build="V800R012C00SPC500",
            kernel_name="vrp",
            hw_model="S5720-28X-SI-AC",
            build_id="V800R012C00SPC500",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "network-os"},
        ),
    ),
    (
        "NETGEAR Firmware V1.0.9.88_10.2.88 R7000",
        None,
        OSData(
            family="network-os",
            vendor="Netgear",
            product="Firmware",
            version_major=1,
            version_minor=0,
            version_patch=9,
            version_build="1.0.9.88_10.2.88",
            kernel_name="firmware",
            hw_model="R7000",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os"},
        ),
    ),
    # Legacy generator coverage (network vendors)
    (
        "Cisco IOS XE Software, Version 17.9.1a (Amsterdam) C9300-24T, universalk9, c9300-universalk9.17.9.1.a.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="universalk9",
            codename="Amsterdam",
            version_major=17,
            version_minor=9,
            version_patch=1,
            version_build="17.9.1a",
            kernel_name="ios-xe",
            hw_model="C9300-24T",
            build_id="c9300-universalk9.17.9.1.a.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.9.1a"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.9.1a:*:universalk9:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.9.1a (Amsterdam) C9300-24T, ipbase, c9300-ipbase.17.9.1.a.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="ipbase",
            codename="Amsterdam",
            version_major=17,
            version_minor=9,
            version_patch=1,
            version_build="17.9.1a",
            kernel_name="ios-xe",
            hw_model="C9300-24T",
            build_id="c9300-ipbase.17.9.1.a.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.9.1a"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.9.1a:*:ipbase:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.9.1a (Amsterdam) C9300-48P, universalk9, c9300-universalk9.17.9.1.a.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="universalk9",
            codename="Amsterdam",
            version_major=17,
            version_minor=9,
            version_patch=1,
            version_build="17.9.1a",
            kernel_name="ios-xe",
            hw_model="C9300-48P",
            build_id="c9300-universalk9.17.9.1.a.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.9.1a"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.9.1a:*:universalk9:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.9.1a (Amsterdam) C9300-48P, ipbase, c9300-ipbase.17.9.1.a.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="ipbase",
            codename="Amsterdam",
            version_major=17,
            version_minor=9,
            version_patch=1,
            version_build="17.9.1a",
            kernel_name="ios-xe",
            hw_model="C9300-48P",
            build_id="c9300-ipbase.17.9.1.a.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.9.1a"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.9.1a:*:ipbase:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.9.3 (Amsterdam) C9300-24T, universalk9, c9300-universalk9.17.9.3.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="universalk9",
            codename="Amsterdam",
            version_major=17,
            version_minor=9,
            version_patch=3,
            version_build="17.9.3",
            kernel_name="ios-xe",
            hw_model="C9300-24T",
            build_id="c9300-universalk9.17.9.3.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.9.3"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.9.3:*:universalk9:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.9.3 (Amsterdam) C9300-24T, ipbase, c9300-ipbase.17.9.3.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="ipbase",
            codename="Amsterdam",
            version_major=17,
            version_minor=9,
            version_patch=3,
            version_build="17.9.3",
            kernel_name="ios-xe",
            hw_model="C9300-24T",
            build_id="c9300-ipbase.17.9.3.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.9.3"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.9.3:*:ipbase:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.9.3 (Amsterdam) C9300-48P, universalk9, c9300-universalk9.17.9.3.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="universalk9",
            codename="Amsterdam",
            version_major=17,
            version_minor=9,
            version_patch=3,
            version_build="17.9.3",
            kernel_name="ios-xe",
            hw_model="C9300-48P",
            build_id="c9300-universalk9.17.9.3.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.9.3"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.9.3:*:universalk9:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.9.3 (Amsterdam) C9300-48P, ipbase, c9300-ipbase.17.9.3.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="ipbase",
            codename="Amsterdam",
            version_major=17,
            version_minor=9,
            version_patch=3,
            version_build="17.9.3",
            kernel_name="ios-xe",
            hw_model="C9300-48P",
            build_id="c9300-ipbase.17.9.3.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.9.3"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.9.3:*:ipbase:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.9.4a (Amsterdam) C9300-24T, universalk9, c9300-universalk9.17.9.4.a.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="universalk9",
            codename="Amsterdam",
            version_major=17,
            version_minor=9,
            version_patch=4,
            version_build="17.9.4a",
            kernel_name="ios-xe",
            hw_model="C9300-24T",
            build_id="c9300-universalk9.17.9.4.a.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.9.4a"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.9.4a:*:universalk9:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.9.4a (Amsterdam) C9300-24T, ipbase, c9300-ipbase.17.9.4.a.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="ipbase",
            codename="Amsterdam",
            version_major=17,
            version_minor=9,
            version_patch=4,
            version_build="17.9.4a",
            kernel_name="ios-xe",
            hw_model="C9300-24T",
            build_id="c9300-ipbase.17.9.4.a.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.9.4a"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.9.4a:*:ipbase:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.9.4a (Amsterdam) C9300-48P, universalk9, c9300-universalk9.17.9.4.a.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="universalk9",
            codename="Amsterdam",
            version_major=17,
            version_minor=9,
            version_patch=4,
            version_build="17.9.4a",
            kernel_name="ios-xe",
            hw_model="C9300-48P",
            build_id="c9300-universalk9.17.9.4.a.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.9.4a"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.9.4a:*:universalk9:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.9.4a (Amsterdam) C9300-48P, ipbase, c9300-ipbase.17.9.4.a.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="ipbase",
            codename="Amsterdam",
            version_major=17,
            version_minor=9,
            version_patch=4,
            version_build="17.9.4a",
            kernel_name="ios-xe",
            hw_model="C9300-48P",
            build_id="c9300-ipbase.17.9.4.a.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.9.4a"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.9.4a:*:ipbase:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.6.5 (Amsterdam) C9300-24T, universalk9, c9300-universalk9.17.6.5.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="universalk9",
            codename="Amsterdam",
            version_major=17,
            version_minor=6,
            version_patch=5,
            version_build="17.6.5",
            kernel_name="ios-xe",
            hw_model="C9300-24T",
            build_id="c9300-universalk9.17.6.5.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.6.5"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.6.5:*:universalk9:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.6.5 (Amsterdam) C9300-24T, ipbase, c9300-ipbase.17.6.5.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="ipbase",
            codename="Amsterdam",
            version_major=17,
            version_minor=6,
            version_patch=5,
            version_build="17.6.5",
            kernel_name="ios-xe",
            hw_model="C9300-24T",
            build_id="c9300-ipbase.17.6.5.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.6.5"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.6.5:*:ipbase:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.6.5 (Amsterdam) C9300-48P, universalk9, c9300-universalk9.17.6.5.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="universalk9",
            codename="Amsterdam",
            version_major=17,
            version_minor=6,
            version_patch=5,
            version_build="17.6.5",
            kernel_name="ios-xe",
            hw_model="C9300-48P",
            build_id="c9300-universalk9.17.6.5.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.6.5"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.6.5:*:universalk9:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS XE Software, Version 17.6.5 (Amsterdam) C9300-48P, ipbase, c9300-ipbase.17.6.5.SPA.bin",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS XE",
            edition="ipbase",
            codename="Amsterdam",
            version_major=17,
            version_minor=6,
            version_patch=5,
            version_build="17.6.5",
            kernel_name="ios-xe",
            hw_model="C9300-48P",
            build_id="c9300-ipbase.17.6.5.SPA.bin",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "17.6.5"},
            os_key="cpe:2.3:o:cisco:ios_xe:17.6.5:*:ipbase:*:*:*:*:*",
        ),
    ),
    (
        "Cisco Nexus Operating System (NX-OS) Software nxos.10.2(3).bin N9K-C93360YC-FX2",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="NX-OS",
            version_major=10,
            version_minor=2,
            version_patch=3,
            version_build="10.2(3)",
            kernel_name="nx-os",
            hw_model="N9K-C93360YC-FX2",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os", "version_raw": "10.2(3)"},
            os_key="cpe:2.3:o:cisco:nx-os:10.2\\(3\\):*:*:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS Software, C2960 Software (C2960-LANBASEK9-M), Version 15.2(7)E3, RELEASE SOFTWARE (fc1)",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS",
            version_major=15,
            version_minor=2,
            version_patch=7,
            version_build="15.2(7)E3",
            kernel_name="ios",
            hw_model="C2960",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os", "version_raw": "15.2(7)E3"},
            os_key="cpe:2.3:o:cisco:ios:15.2\\(7\\)E3:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Cisco IOS Software, C2960 Software (C2960-LANBASEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1)",
        None,
        OSData(
            family="network-os",
            vendor="Cisco",
            product="IOS",
            version_major=12,
            version_minor=4,
            version_patch=25,
            version_build="12.4(25d",
            kernel_name="ios",
            hw_model="C2960",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os", "version_raw": "12.4(25d"},
            os_key="cpe:2.3:o:cisco:ios:12.4\\(25d:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 20.4R3-S3 jinstall-ex-4300-20.4R3-S3.tgz EX3400-24P",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=20,
            version_minor=4,
            version_build="20.4R3-S3",
            kernel_name="junos",
            hw_model="EX3400-24P",
            build_id="jinstall-ex-4300-20.4R3-S3.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "20.4R3-S3"},
            os_key="cpe:2.3:o:juniper:junos:20.4r3-s3:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 20.4R3-S3 jinstall-ex-4300-20.4R3-S3.tgz SRX300",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=20,
            version_minor=4,
            version_build="20.4R3-S3",
            kernel_name="junos",
            hw_model="SRX300",
            build_id="jinstall-ex-4300-20.4R3-S3.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "20.4R3-S3"},
            os_key="cpe:2.3:o:juniper:junos:20.4r3-s3:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 20.4R3-S3 jinstall-ex-4300-20.4R3-S3.tgz QFX5120-48Y",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=20,
            version_minor=4,
            version_build="20.4R3-S3",
            kernel_name="junos",
            hw_model="QFX5120",
            build_id="jinstall-ex-4300-20.4R3-S3.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "20.4R3-S3"},
            os_key="cpe:2.3:o:juniper:junos:20.4r3-s3:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 18.4R2-S4 jinstall-ex-4300-18.4R2-S4.tgz EX4300-48T",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=18,
            version_minor=4,
            version_build="18.4R2-S4",
            kernel_name="junos",
            hw_model="EX4300-48T",
            build_id="jinstall-ex-4300-18.4R2-S4.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "18.4R2-S4"},
            os_key="cpe:2.3:o:juniper:junos:18.4r2-s4:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 18.4R2-S4 jinstall-ex-4300-18.4R2-S4.tgz EX3400-24P",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=18,
            version_minor=4,
            version_build="18.4R2-S4",
            kernel_name="junos",
            hw_model="EX3400-24P",
            build_id="jinstall-ex-4300-18.4R2-S4.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "18.4R2-S4"},
            os_key="cpe:2.3:o:juniper:junos:18.4r2-s4:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 18.4R2-S4 jinstall-ex-4300-18.4R2-S4.tgz SRX300",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=18,
            version_minor=4,
            version_build="18.4R2-S4",
            kernel_name="junos",
            hw_model="SRX300",
            build_id="jinstall-ex-4300-18.4R2-S4.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "18.4R2-S4"},
            os_key="cpe:2.3:o:juniper:junos:18.4r2-s4:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 18.4R2-S4 jinstall-ex-4300-18.4R2-S4.tgz QFX5120-48Y",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=18,
            version_minor=4,
            version_build="18.4R2-S4",
            kernel_name="junos",
            hw_model="QFX5120",
            build_id="jinstall-ex-4300-18.4R2-S4.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "18.4R2-S4"},
            os_key="cpe:2.3:o:juniper:junos:18.4r2-s4:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 21.1R1 jinstall-ex-4300-21.1R1.tgz EX4300-48T",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=21,
            version_minor=1,
            version_build="21.1R1",
            kernel_name="junos",
            hw_model="EX4300-48T",
            build_id="jinstall-ex-4300-21.1R1.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "21.1R1"},
            os_key="cpe:2.3:o:juniper:junos:21.1r1:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 21.1R1 jinstall-ex-4300-21.1R1.tgz EX3400-24P",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=21,
            version_minor=1,
            version_build="21.1R1",
            kernel_name="junos",
            hw_model="EX3400-24P",
            build_id="jinstall-ex-4300-21.1R1.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "21.1R1"},
            os_key="cpe:2.3:o:juniper:junos:21.1r1:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 21.1R1 jinstall-ex-4300-21.1R1.tgz SRX300",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=21,
            version_minor=1,
            version_build="21.1R1",
            kernel_name="junos",
            hw_model="SRX300",
            build_id="jinstall-ex-4300-21.1R1.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "21.1R1"},
            os_key="cpe:2.3:o:juniper:junos:21.1r1:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 21.1R1 jinstall-ex-4300-21.1R1.tgz QFX5120-48Y",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=21,
            version_minor=1,
            version_build="21.1R1",
            kernel_name="junos",
            hw_model="QFX5120",
            build_id="jinstall-ex-4300-21.1R1.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "21.1R1"},
            os_key="cpe:2.3:o:juniper:junos:21.1r1:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 19.4R3 jinstall-ex-4300-19.4R3.tgz EX4300-48T",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=19,
            version_minor=4,
            version_build="19.4R3",
            kernel_name="junos",
            hw_model="EX4300-48T",
            build_id="jinstall-ex-4300-19.4R3.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "19.4R3"},
            os_key="cpe:2.3:o:juniper:junos:19.4r3:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 19.4R3 jinstall-ex-4300-19.4R3.tgz EX3400-24P",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=19,
            version_minor=4,
            version_build="19.4R3",
            kernel_name="junos",
            hw_model="EX3400-24P",
            build_id="jinstall-ex-4300-19.4R3.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "19.4R3"},
            os_key="cpe:2.3:o:juniper:junos:19.4r3:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 19.4R3 jinstall-ex-4300-19.4R3.tgz SRX300",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=19,
            version_minor=4,
            version_build="19.4R3",
            kernel_name="junos",
            hw_model="SRX300",
            build_id="jinstall-ex-4300-19.4R3.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "19.4R3"},
            os_key="cpe:2.3:o:juniper:junos:19.4r3:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 19.4R3 jinstall-ex-4300-19.4R3.tgz QFX5120-48Y",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=19,
            version_minor=4,
            version_build="19.4R3",
            kernel_name="junos",
            hw_model="QFX5120",
            build_id="jinstall-ex-4300-19.4R3.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "19.4R3"},
            os_key="cpe:2.3:o:juniper:junos:19.4r3:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 22.3R1-S1 jinstall-ex-4300-22.3R1-S1.tgz EX4300-48T",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=22,
            version_minor=3,
            version_build="22.3R1-S1",
            kernel_name="junos",
            hw_model="EX4300-48T",
            build_id="jinstall-ex-4300-22.3R1-S1.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "22.3R1-S1"},
            os_key="cpe:2.3:o:juniper:junos:22.3r1-s1:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 22.3R1-S1 jinstall-ex-4300-22.3R1-S1.tgz EX3400-24P",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=22,
            version_minor=3,
            version_build="22.3R1-S1",
            kernel_name="junos",
            hw_model="EX3400-24P",
            build_id="jinstall-ex-4300-22.3R1-S1.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "22.3R1-S1"},
            os_key="cpe:2.3:o:juniper:junos:22.3r1-s1:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 22.3R1-S1 jinstall-ex-4300-22.3R1-S1.tgz SRX300",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=22,
            version_minor=3,
            version_build="22.3R1-S1",
            kernel_name="junos",
            hw_model="SRX300",
            build_id="jinstall-ex-4300-22.3R1-S1.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "22.3R1-S1"},
            os_key="cpe:2.3:o:juniper:junos:22.3r1-s1:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Junos: 22.3R1-S1 jinstall-ex-4300-22.3R1-S1.tgz QFX5120-48Y",
        None,
        OSData(
            family="network-os",
            vendor="Juniper",
            product="Junos",
            version_major=22,
            version_minor=3,
            version_build="22.3R1-S1",
            kernel_name="junos",
            hw_model="QFX5120",
            build_id="jinstall-ex-4300-22.3R1-S1.tgz",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os", "version_raw": "22.3R1-S1"},
            os_key="cpe:2.3:o:juniper:junos:22.3r1-s1:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-60E FGT60E v7.2.7 build1600 (GA) FGT_7.2.7-build1600",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=7,
            version_minor=2,
            version_patch=7,
            version_build="7.2.7+build.1600",
            kernel_name="fortios",
            hw_model="FG-60E",
            build_id="FGT_7.2.7-build1600",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.2.7:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-200E v7.2.7 build1600 (GA) FGT_7.2.7-build1600",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=7,
            version_minor=2,
            version_patch=7,
            version_build="7.2.7+build.1600",
            kernel_name="fortios",
            hw_model="FG-200E",
            build_id="FGT_7.2.7-build1600",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.2.7:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-80F FGT80F v7.2.7 build1600 (GA) FGT_7.2.7-build1600",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=7,
            version_minor=2,
            version_patch=7,
            version_build="7.2.7+build.1600",
            kernel_name="fortios",
            hw_model="FG-80F",
            build_id="FGT_7.2.7-build1600",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.2.7:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-100F v7.0.13 build1520 (Patch) FGT_7.0.13-build1520",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="PATCH",
            version_major=7,
            version_minor=0,
            version_patch=13,
            version_build="7.0.13+build.1520",
            kernel_name="fortios",
            hw_model="FG-100F",
            build_id="FGT_7.0.13-build1520",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.0.13:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-60E FGT60E v7.0.13 build1520 (Patch) FGT_7.0.13-build1520",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="PATCH",
            version_major=7,
            version_minor=0,
            version_patch=13,
            version_build="7.0.13+build.1520",
            kernel_name="fortios",
            hw_model="FG-60E",
            build_id="FGT_7.0.13-build1520",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.0.13:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-200E v7.0.13 build1520 (Patch) FGT_7.0.13-build1520",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="PATCH",
            version_major=7,
            version_minor=0,
            version_patch=13,
            version_build="7.0.13+build.1520",
            kernel_name="fortios",
            hw_model="FG-200E",
            build_id="FGT_7.0.13-build1520",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.0.13:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-80F FGT80F v7.0.13 build1520 (Patch) FGT_7.0.13-build1520",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="PATCH",
            version_major=7,
            version_minor=0,
            version_patch=13,
            version_build="7.0.13+build.1520",
            kernel_name="fortios",
            hw_model="FG-80F",
            build_id="FGT_7.0.13-build1520",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.0.13:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-100F v6.4.14 build1960 (GA) FGT_6.4.14-build1960",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=6,
            version_minor=4,
            version_patch=14,
            version_build="6.4.14+build.1960",
            kernel_name="fortios",
            hw_model="FG-100F",
            build_id="FGT_6.4.14-build1960",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:6.4.14:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-60E FGT60E v6.4.14 build1960 (GA) FGT_6.4.14-build1960",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=6,
            version_minor=4,
            version_patch=14,
            version_build="6.4.14+build.1960",
            kernel_name="fortios",
            hw_model="FG-60E",
            build_id="FGT_6.4.14-build1960",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:6.4.14:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-200E v6.4.14 build1960 (GA) FGT_6.4.14-build1960",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=6,
            version_minor=4,
            version_patch=14,
            version_build="6.4.14+build.1960",
            kernel_name="fortios",
            hw_model="FG-200E",
            build_id="FGT_6.4.14-build1960",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:6.4.14:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-80F FGT80F v6.4.14 build1960 (GA) FGT_6.4.14-build1960",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=6,
            version_minor=4,
            version_patch=14,
            version_build="6.4.14+build.1960",
            kernel_name="fortios",
            hw_model="FG-80F",
            build_id="FGT_6.4.14-build1960",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:6.4.14:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-100F v7.4.3 build2580 (GA) FGT_7.4.3-build2580",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=7,
            version_minor=4,
            version_patch=3,
            version_build="7.4.3+build.2580",
            kernel_name="fortios",
            hw_model="FG-100F",
            build_id="FGT_7.4.3-build2580",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.4.3:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-60E FGT60E v7.4.3 build2580 (GA) FGT_7.4.3-build2580",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=7,
            version_minor=4,
            version_patch=3,
            version_build="7.4.3+build.2580",
            kernel_name="fortios",
            hw_model="FG-60E",
            build_id="FGT_7.4.3-build2580",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.4.3:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-200E v7.4.3 build2580 (GA) FGT_7.4.3-build2580",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=7,
            version_minor=4,
            version_patch=3,
            version_build="7.4.3+build.2580",
            kernel_name="fortios",
            hw_model="FG-200E",
            build_id="FGT_7.4.3-build2580",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.4.3:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-80F FGT80F v7.4.3 build2580 (GA) FGT_7.4.3-build2580",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=7,
            version_minor=4,
            version_patch=3,
            version_build="7.4.3+build.2580",
            kernel_name="fortios",
            hw_model="FG-80F",
            build_id="FGT_7.4.3-build2580",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.4.3:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-100F v7.2.5 build1500 (GA) FGT_7.2.5-build1500",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=7,
            version_minor=2,
            version_patch=5,
            version_build="7.2.5+build.1500",
            kernel_name="fortios",
            hw_model="FG-100F",
            build_id="FGT_7.2.5-build1500",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.2.5:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-60E FGT60E v7.2.5 build1500 (GA) FGT_7.2.5-build1500",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=7,
            version_minor=2,
            version_patch=5,
            version_build="7.2.5+build.1500",
            kernel_name="fortios",
            hw_model="FG-60E",
            build_id="FGT_7.2.5-build1500",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.2.5:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-200E v7.2.5 build1500 (GA) FGT_7.2.5-build1500",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=7,
            version_minor=2,
            version_patch=5,
            version_build="7.2.5+build.1500",
            kernel_name="fortios",
            hw_model="FG-200E",
            build_id="FGT_7.2.5-build1500",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.2.5:*:*:*:*:*:*:*",
        ),
    ),
    (
        "FortiGate-80F FGT80F v7.2.5 build1500 (GA) FGT_7.2.5-build1500",
        None,
        OSData(
            family="network-os",
            vendor="Fortinet",
            product="FortiOS",
            channel="GA",
            version_major=7,
            version_minor=2,
            version_patch=5,
            version_build="7.2.5+build.1500",
            kernel_name="fortios",
            hw_model="FG-80F",
            build_id="FGT_7.2.5-build1500",
            precision="build",
            confidence=0.85,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:fortinet:fortios:7.2.5:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Huawei VRP V200R019C10SPC300 S5720-28X-SI-AC",
        None,
        OSData(
            family="network-os",
            vendor="Huawei",
            product="VRP",
            version_major=200,
            version_minor=19,
            version_build="V200R019C10SPC300",
            kernel_name="vrp",
            hw_model="S5720-28X-SI-AC",
            build_id="V200R019C10SPC300",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:huawei:vrp:V200R019C10SPC300:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Huawei VRP V300R020C00 S5720-28X-SI-AC",
        None,
        OSData(
            family="network-os",
            vendor="Huawei",
            product="VRP",
            version_major=300,
            version_minor=20,
            version_build="V300R020C00",
            kernel_name="vrp",
            hw_model="S5720-28X-SI-AC",
            build_id="V300R020C00",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:huawei:vrp:V300R020C00:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Huawei VRP V500R021C00SPC200 S5720-28X-SI-AC",
        None,
        OSData(
            family="network-os",
            vendor="Huawei",
            product="VRP",
            version_major=500,
            version_minor=21,
            version_build="V500R021C00SPC200",
            kernel_name="vrp",
            hw_model="S5720-28X-SI-AC",
            build_id="V500R021C00SPC200",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:huawei:vrp:V500R021C00SPC200:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Huawei VRP V800R012C00SPC500 CE6857-48S6C",
        None,
        OSData(
            family="network-os",
            vendor="Huawei",
            product="VRP",
            version_major=800,
            version_minor=12,
            version_build="V800R012C00SPC500",
            kernel_name="vrp",
            hw_model="CE6857-",
            build_id="V800R012C00SPC500",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:huawei:vrp:V800R012C00SPC500:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Huawei VRP V200R019C10SPC300 CE6857-48S6C",
        None,
        OSData(
            family="network-os",
            vendor="Huawei",
            product="VRP",
            version_major=200,
            version_minor=19,
            version_build="V200R019C10SPC300",
            kernel_name="vrp",
            hw_model="CE6857-",
            build_id="V200R019C10SPC300",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:huawei:vrp:V200R019C10SPC300:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Huawei VRP V300R020C00 CE6857-48S6C",
        None,
        OSData(
            family="network-os",
            vendor="Huawei",
            product="VRP",
            version_major=300,
            version_minor=20,
            version_build="V300R020C00",
            kernel_name="vrp",
            hw_model="CE6857-",
            build_id="V300R020C00",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:huawei:vrp:V300R020C00:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Huawei VRP V500R021C00SPC200 CE6857-48S6C",
        None,
        OSData(
            family="network-os",
            vendor="Huawei",
            product="VRP",
            version_major=500,
            version_minor=21,
            version_build="V500R021C00SPC200",
            kernel_name="vrp",
            hw_model="CE6857-",
            build_id="V500R021C00SPC200",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:huawei:vrp:V500R021C00SPC200:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Huawei VRP V800R012C00SPC500 AR1220",
        None,
        OSData(
            family="network-os",
            vendor="Huawei",
            product="VRP",
            version_major=800,
            version_minor=12,
            version_build="V800R012C00SPC500",
            kernel_name="vrp",
            hw_model="AR1220",
            build_id="V800R012C00SPC500",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:huawei:vrp:V800R012C00SPC500:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Huawei VRP V200R019C10SPC300 AR1220",
        None,
        OSData(
            family="network-os",
            vendor="Huawei",
            product="VRP",
            version_major=200,
            version_minor=19,
            version_build="V200R019C10SPC300",
            kernel_name="vrp",
            hw_model="AR1220",
            build_id="V200R019C10SPC300",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:huawei:vrp:V200R019C10SPC300:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Huawei VRP V300R020C00 AR1220",
        None,
        OSData(
            family="network-os",
            vendor="Huawei",
            product="VRP",
            version_major=300,
            version_minor=20,
            version_build="V300R020C00",
            kernel_name="vrp",
            hw_model="AR1220",
            build_id="V300R020C00",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:huawei:vrp:V300R020C00:*:*:*:*:*:*:*",
        ),
    ),
    (
        "Huawei VRP V500R021C00SPC200 AR1220",
        None,
        OSData(
            family="network-os",
            vendor="Huawei",
            product="VRP",
            version_major=500,
            version_minor=21,
            version_build="V500R021C00SPC200",
            kernel_name="vrp",
            hw_model="AR1220",
            build_id="V500R021C00SPC200",
            precision="minor",
            confidence=0.75,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:huawei:vrp:V500R021C00SPC200:*:*:*:*:*:*:*",
        ),
    ),
    (
        "NETGEAR Firmware V1.0.11.110_10.2.100 R7000",
        None,
        OSData(
            family="network-os",
            vendor="Netgear",
            product="Firmware",
            version_major=1,
            version_minor=0,
            version_patch=11,
            version_build="1.0.11.110_10.2.100",
            kernel_name="firmware",
            hw_model="R7000",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:netgear:firmware:1.0.11.110_10.2.100:*:*:*:*:*:*:*",
        ),
    ),
    (
        "NETGEAR Firmware V1.0.4.120_2.0.83 R7000",
        None,
        OSData(
            family="network-os",
            vendor="Netgear",
            product="Firmware",
            version_major=1,
            version_minor=0,
            version_patch=4,
            version_build="1.0.4.120_2.0.83",
            kernel_name="firmware",
            hw_model="R7000",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:netgear:firmware:1.0.4.120_2.0.83:*:*:*:*:*:*:*",
        ),
    ),
    (
        "NETGEAR Firmware V1.0.9.88_10.2.88 R8000",
        None,
        OSData(
            family="network-os",
            vendor="Netgear",
            product="Firmware",
            version_major=1,
            version_minor=0,
            version_patch=9,
            version_build="1.0.9.88_10.2.88",
            kernel_name="firmware",
            hw_model="R8000",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:netgear:firmware:1.0.9.88_10.2.88:*:*:*:*:*:*:*",
        ),
    ),
    (
        "NETGEAR Firmware V1.0.11.110_10.2.100 R8000",
        None,
        OSData(
            family="network-os",
            vendor="Netgear",
            product="Firmware",
            version_major=1,
            version_minor=0,
            version_patch=11,
            version_build="1.0.11.110_10.2.100",
            kernel_name="firmware",
            hw_model="R8000",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:netgear:firmware:1.0.11.110_10.2.100:*:*:*:*:*:*:*",
        ),
    ),
    (
        "NETGEAR Firmware V1.0.4.120_2.0.83 R8000",
        None,
        OSData(
            family="network-os",
            vendor="Netgear",
            product="Firmware",
            version_major=1,
            version_minor=0,
            version_patch=4,
            version_build="1.0.4.120_2.0.83",
            kernel_name="firmware",
            hw_model="R8000",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:netgear:firmware:1.0.4.120_2.0.83:*:*:*:*:*:*:*",
        ),
    ),
    (
        "NETGEAR Firmware V1.0.9.88_10.2.88 RAX50",
        None,
        OSData(
            family="network-os",
            vendor="Netgear",
            product="Firmware",
            version_major=1,
            version_minor=0,
            version_patch=9,
            version_build="1.0.9.88_10.2.88",
            kernel_name="firmware",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:netgear:firmware:1.0.9.88_10.2.88:*:*:*:*:*:*:*",
        ),
    ),
    (
        "NETGEAR Firmware V1.0.11.110_10.2.100 RAX50",
        None,
        OSData(
            family="network-os",
            vendor="Netgear",
            product="Firmware",
            version_major=1,
            version_minor=0,
            version_patch=11,
            version_build="1.0.11.110_10.2.100",
            kernel_name="firmware",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:netgear:firmware:1.0.11.110_10.2.100:*:*:*:*:*:*:*",
        ),
    ),
    (
        "NETGEAR Firmware V1.0.4.120_2.0.83 RAX50",
        None,
        OSData(
            family="network-os",
            vendor="Netgear",
            product="Firmware",
            version_major=1,
            version_minor=0,
            version_patch=4,
            version_build="1.0.4.120_2.0.83",
            kernel_name="firmware",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:netgear:firmware:1.0.4.120_2.0.83:*:*:*:*:*:*:*",
        ),
    ),
    (
        "NETGEAR Firmware V1.0.9.88_10.2.88 R6400",
        None,
        OSData(
            family="network-os",
            vendor="Netgear",
            product="Firmware",
            version_major=1,
            version_minor=0,
            version_patch=9,
            version_build="1.0.9.88_10.2.88",
            kernel_name="firmware",
            hw_model="R6400",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:netgear:firmware:1.0.9.88_10.2.88:*:*:*:*:*:*:*",
        ),
    ),
    (
        "NETGEAR Firmware V1.0.11.110_10.2.100 R6400",
        None,
        OSData(
            family="network-os",
            vendor="Netgear",
            product="Firmware",
            version_major=1,
            version_minor=0,
            version_patch=11,
            version_build="1.0.11.110_10.2.100",
            kernel_name="firmware",
            hw_model="R6400",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:netgear:firmware:1.0.11.110_10.2.100:*:*:*:*:*:*:*",
        ),
    ),
    (
        "NETGEAR Firmware V1.0.4.120_2.0.83 R6400",
        None,
        OSData(
            family="network-os",
            vendor="Netgear",
            product="Firmware",
            version_major=1,
            version_minor=0,
            version_patch=4,
            version_build="1.0.4.120_2.0.83",
            kernel_name="firmware",
            hw_model="R6400",
            precision="patch",
            confidence=0.8,
            evidence={"hit": "network-os"},
            os_key="cpe:2.3:o:netgear:firmware:1.0.4.120_2.0.83:*:*:*:*:*:*:*",
        ),
    ),
]


@pytest.mark.parametrize(("text", "data", "expected"), build_params("network", NETWORK_OSDATA_CASES))
def test_network_normalize_os(text: str, data: dict | None, expected: OSData) -> None:
    """Ensure network inputs normalize into the expected OSData payloads."""
    result = normalize_os(text, data)
    assert result == expected
